### ISSUE TITLE
Práctico 5 y 6

### ISSUE THREAD

**Issue by jaarac** [facunava92/VxC_Grupo6#1]
Se debe transformar la selección, no la imagen completa.

**Comment by facunava92** [comment]
Fuimos añadiendo funcionalidad al código 4, se trabaja con una ROI, la cual en un principio es la imagen completa, pero seleccionando con el mouse se modifica la ROI y la transformación se hace sobre la última ROI

**Comment by facunava92** [comment]
Corregido segun lo charlado en el coloquio.
