### ISSUE TITLE
Práctico 7

### ISSUE THREAD

**Issue by jaarac** [facunava92/VxC_Grupo6#2]
Se deben seleccionar 3 puntos en una imagen e incrustar en esos tres puntos otra imagen usando una transformación afín.
No hay que seleccionar 2 veces 3 puntos.

**Comment by facunava92** [comment]
La segunda selección sirve para poder darle orientación para que lograr el efecto de la “publicidad” que nos habían mostrado, sino era muy difícil adivinar esos puntos destino

**Comment by facunava92** [comment]
Demostrado en el coloquio.
